import numpy as np
import fatiando as ft

shape = (21, 21)
x, y = ft.grd.regular((-10, 10, 30, 50), shape)
height = -800*ft.utils.gaussian2d(x, y, 5, 5, x0=0, y0=40)
rel = -7000*ft.utils.gaussian2d(x, y, 10, 20, x0=0, y0=45)
thick = height - rel
dens = 1900*np.ones_like(thick)
data = np.transpose([x, y, height, thick, dens])
with open('layers.txt', 'w') as f:
    f.write("# Synthetic layer model of sediments and topography\n")
    f.write("#   lon   lat   height   thickness   density\n")
    np.savetxt(f, data, fmt='%g')
ft.vis.figure()
ft.vis.title('Depth of sediments [m]')
ft.vis.axis('scaled')
ft.vis.pcolor(x, y, rel, shape)
ft.vis.colorbar()
ft.vis.xlabel('Longitude')
ft.vis.ylabel('Latitude')
ft.vis.figure()
ft.vis.title('Topography [m]')
ft.vis.axis('scaled')
ft.vis.pcolor(x, y, height, shape)
ft.vis.colorbar()
ft.vis.xlabel('Longitude')
ft.vis.ylabel('Latitude')
ft.vis.figure()
ft.vis.title('Thickness of sediment layer [m]')
ft.vis.axis('scaled')
ft.vis.pcolor(x, y, thick, shape)
ft.vis.colorbar()
ft.vis.xlabel('Longitude')
ft.vis.ylabel('Latitude')
ft.vis.show()
