all: Doxyfile
	doxygen
	cp images/logo.png build/html
	cp tabs.css build/html
	cp images/tab_*.png build/html
	cp images/subtab_*.png build/html
	cp images/logo.ico build/html

win: Doxyfile
	doxygen
	copy images\logo.png build\html
	copy tabs.css build\html
	copy images\tab_*.png build\html
	copy images\subtab_*.png build\html
	copy images\logo.ico build\html
