#!/usr/bin/env python
################################################################################
#
#    Copyright (C) 2009  Leonardo Uieda
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#    Doubts and/or suggestions please mail the author:
#         Leonardo Uieda - leouieda@gmail.com
#
################################################################################
"""
TessPot:
    Calculate the gravitational potential of a tesseroid model.
"""
################################################################################
# Created on 6-May-2009 10:05 PM
# Last modified by $Author$
__author__ = 'Leonardo Uieda (leouieda@gmail.com)'
__version__ = '$Revision$'
__date__ = '$Date$'
__copyright__ = "Copyright (C) 2009  Leonardo Uieda"
__license__ = "GPL"
################################################################################

import os
import sys

# Get the path of where the program is
mypath = os.path.abspath(os.path.dirname(sys.argv[0]))
# Get the path os the mods
tmp = mypath + os.path.sep + 'mods'
modspath = os.path.abspath(tmp)
# Add this path to the sys.path so that the modules can be imported
sys.path.append(modspath)
# Now the mod can be imported
from tessgravmain import Main
import tesseroidgravity as tg

if __name__ == '__main__':

    name = 'TessPot'
    description = "  Calculates the gravitational potential generated by a " + \
                  "tesseroid model."

    main = Main(name, description, sys.argv, tg.TesseroidPotential, \
                version='0.1')
    main.start()
    sys.exit()
